services:
  node_app:
    container_name: node_app
    build: ./back-end
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./back-end/.env
  
  react_vite_app:
    container_name: react_vite_app
    build: ./front-end
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - node_app
      